### PR TITLE
Make it possible to start an app without any directory structure present

### LINKED ISSUE #25: Need option to exempt JS files from minification but still expose them to public

### LINKED ISSUE #90: Templating engine agnosticism incompatible with defaultErrorPages
Dropping teddy will break the default error pages. We should probably make teddy a hard dependency and an always-supported view engine just for the default error pages, while still of course allowing users to add other view engines as well as change the default.

### LINKED ISSUE #108: Line numbers on HTML validator source code should not be selectable

### LINKED ISSUE #259: Improvement: https option object
Roll all of the https options into a single object for better clarity. Possible format:

```
"https": {
  "enable": true,
  "httpsOnly": true,
  "port": 443,
  "pfx": true, # delete this
  "keyPath": {
    "pfx": "some/file/path", # use the inclusion of this instead to determine (pfx or key/cert)
    "key": "other/file/path",
    "cert": "next/file/path"
  },
  "passphrase": "pw",
  "ca": ["string", "or", "array"],
  "requestCert": true,
  "rejectUnauthorized": true
}
```

### LINKED ISSUE #286: Ability to instantiate an app with nothing but package.json
All other boilerplate created merely by requiring roosevelt and calling `startServer()`.

### LINKED ISSUE #290: Refactor command line args for consistency, stylistic conformance to common patterns, and add shorthands
Revised in accordance with [UNIX conventions](https://unix.stackexchange.com/questions/21852/single-dashes-for-single-character-options-but-double-dashes-for-words):

We currently have:

- `-dev`
- `-prod`
- `-cores`
- `enable-validator`
- `disable-validator`
- `detach-validator`
- `attach-validator`

It should change to:

- `--development-mode`
  - Shorthand: `--dev`
  - Shorthand: `-d`
- `--production-mode`
  - Shorthand: `--prod`
  - Shorthand: `-p`
- `--cores`
  - Shorthand: `-c`
- `--enable-validator`
  - Shorthand: `--html-validator`
  - Shorthand: `-h`
- `--disable-validator`
  - Shorthand: `--raw`
  - Shorthand: `-r`
- `--background-validator`
  - Shorthand: `-b`
- `--attach-validator`
  - Shorthand: `-a`

Deprecated syntax:
- `-dev`
  - Replaced by: `--development-mode`
    - Shorthand: `--dev`
    - Shorthand: `-d`
- `-prod`
  - Replaced by: `--production-mode`
    - Shorthand: `--prod`
    - Shorthand: `-p`
- `-cores`
  - Replaced by: `--cores`
    - Shorthand: `-c`
- `enable-validator`
  - Replaced by: `--enable-validator`
    - Shorthand: `--html-validator`
    - Shorthand: `-h`
- `disable-validator`
  - Replaced by: `--disable-validator`
    - Shorthand: `--raw`
    - Shorthand: `-r`
- `detach-validator`
  - Replaced by: `--background-validator`
    - Shorthand: `-b`
- `attach-validator`
  - Replaced by: `--attach-validator`
    - Shorthand: `-a`

The single character shorthands should also support chaining: e.g. `node app.js -db` would be short for `node app.js --development-mode --background-validator`.

This change will only be merged when we're ready to release 0.11.0.

The deprecated syntax will still be supported during 0.11.x, but will trigger a deprecation warning and will be removed in 0.12.0 or 1.0.0, whichever comes first.

### LINKED ISSUE #292: App blocking errors should exit status one
Errors that block the starting of Roosevelt like the, [jsCompiler failing to initialize](https://github.com/rooseveltframework/roosevelt/blob/27a025192ea6b597b5c2c29f6cebc20505dd580e/lib/jsCompiler.js#L147), should exit status 1 ([process.exit(1)](https://nodejs.org/api/process.html#process_process_exit_code)). This prevents use cases like testing giving false positives, if app initialization/starting fails

### PR DESCRIPTION
**Pull request by Autre31415**
- Create mvc directories if they don't exist.
- Ensure favicon file exists before utilizing it, and print a warning if it doesn't.
- Allow `null` to disable js/css compilers and viewEngine.
- When roosevelt fails to require js/css preprocessor node_module, disable it after printing the error.
- Automatically symlink jsPath and cssPath to statics when js/css compilers are off and they aren't set to be symlinked already.
- Removed all instances of manual slashes being appended to paths in sourceParams.
- Replace instances of manual path concats with `path.join`.
- Render defaultErrorPages natively. (Closes #90)
- Add `generateFolderStructure` param which is disabled by default when Roosevelt is initialized via constructor without a package file.
- Add an internal `fsr` module which includes common file/directory writing methods and checks `generateFolderStructure` before writing anything.
- Move `fileExists` and `symlinkExists` to `fsr`.
- Make it possible to start an app without any package files. (Closes #286)
- Add more command line flags. (Closes #290)
- Ensure app crashing errors exit with code 1 (Closes #292)
- Merge HTTPS params into a single object. (Closes #259)
- Add jsCompilerBlacklist param for exempting JS files from minification while still exposing them to public. (Closes #25)
- Rewrite HTML validator express logic to add support for more response methods.
- Declutter the lib folder.
- Set `favicon`, `viewEngine`, `cssCompiler`, and `jsCompiler` to `"none"` by default.
- Eliminate `getAppDir`.
- Enhance line numbers in HTML validator error page markup display. (Closes #108)
- Add `sourceFlags` internal module to parse command line arguments.

### CODE REVIEW

File: lib/mapRoutes.js [hunk 1]
```diff
@@ -60,16 +62,40 @@ module.exports = function (app) {
...
+  }
+
+  // if js and/or css compilers are disabled, check that jsPath and cssPath are set to be symlinked
+  if (params.cssCompiler === 'none' || params.cssCompiler === null) {
+    basicCSSPath = params.cssPath.replace(params.staticsRoot, '')
+    if (basicCSSPath.charAt(0) === path.sep) {
+      basicCSSPath = basicCSSPath.substr(1)
+    }
+    if (!(basicCSSPath in params.symlinksToStatics)) {
+      logger.warn('Adding CSS directory to symlinksToStatics list'.yellow)
```
Comment (kethinov) [inline lib/mapRoutes.js]: Make this a log, not a warning. And make it say (in blue symlink log text): "📁  [appname] making new symlink [public path in yellow] pointing to [statics path in yellow]"

File: lib/mapRoutes.js [hunk 2]
```diff
@@ -60,16 +62,40 @@ module.exports = function (app) {
...
+      params.symlinksToStatics.unshift(basicCSSPath)
+    }
+  }
+  if (params.jsCompiler === 'none' || params.jsCompiler === null) {
+    basicJSPath = params.jsPath.replace(params.staticsRoot, '')
+    if (basicJSPath.charAt(0) === path.sep) {
+      basicJSPath = basicJSPath.substr(1)
+    }
+    if (!(basicJSPath in params.symlinksToStatics)) {
+      logger.warn('Adding JS directory to symlinksToStatics list'.yellow)
```
Comment (kethinov) [inline lib/mapRoutes.js]: Make this a log, not a warning. And make it say (in blue symlink log text): "📁  [appname] making new symlink [public path in yellow] pointing to [statics path in yellow]"

File: lib/jsCompiler.js [hunk 3]
```diff
@@ -13,26 +13,31 @@ const getFunctionArgs = require('./getFunctionArgs')
...
   }
 
+  preprocessor = params.jsCompiler.nodeModule
+
   // require preprocessor
   try {
     preprocessorModule = prequire(preprocessor)
   } catch (err) {
-    logger.error(`${appName} failed to include your JS compiler! Please ensure that it is declared properly in your package.json and that it has been properly insalled to node_modules.\n`.red, err)
+    logger.error(`${appName} failed to include your JS compiler! Please ensure that it is declared properly in your package.json and that it has been properly insalled to node_modules.`.red)
```
Comment (kethinov) [inline lib/jsCompiler.js]: fix "insalled"

File: lib/preprocessCss.js [hunk 4]
```diff
@@ -13,28 +12,33 @@ const getFunctionArgs = require('./getFunctionArgs')
...
   }
 
+  preprocessor = params.cssCompiler.nodeModule
+
   // require preprocessor
   try {
     preprocessorModule = prequire(preprocessor)
   } catch (err) {
-    logger.error(`${appName} failed to include your CSS preprocessor! Please ensure that it is declared properly in your package.json and that it has been properly insalled to node_modules.\n`.red, err)
+    logger.error(`${appName} failed to include your CSS preprocessor! Please ensure that it is declared properly in your package.json and that it has been properly insalled to node_modules.`.red)
```
Comment (kethinov) [inline lib/preprocessCss.js]: fix "insalled"

File: lib/sourceParams.js [hunk 5]
```diff
@@ -7,14 +7,28 @@ const fileExists = require('./fileExists')
...
 
+  // determine if app has a package.json
+  try {
+    pkg = require(path.join(appDir, 'package.json'))
+  } catch (e) {
+    pkg = {}
+
+    // default folder structure generation to false when it's not set in the constructor
+    if (!params.generateFolderStructure) {
+      logger.warn(`Roosevelt initialized in ${appDir} via constructor with no package.json found. No files will be generated unless param generateFolderStructure is set to true. Only do this if you are sure you want files generated in ${appDir}!`.bold.yellow)
```
Comment (kethinov) [inline lib/sourceParams.js]:
```javascript
logger.warn(`Roosevelt initialized via constructor with no package.json found. No files will be auto-generated unless you set param "generateFolderStructure" to true in the constructor as well. Only do that if you're sure you want Roosevelt to generate files in ${appDir}!`.bold.yellow)
```

File: lib/sourceParams.js [hunk 6]
```diff
@@ -7,14 +7,28 @@ const fileExists = require('./fileExists')
...
+      params.generateFolderStructure = false
```
Comment (kethinov) [inline lib/sourceParams.js]: make sure this is set to true if the app does have a package.json

also make sure to document this param in the README

File: roosevelt.js [hunk 7]
```diff
@@ -111,8 +113,13 @@ module.exports = function (params) {
...
 
   // enable favicon support
-  if (app.get('params').favicon !== 'none') {
-    app.use(require('serve-favicon')(path.join(app.get('appDir'), app.get('params').staticsRoot, app.get('params').favicon)))
+  if (app.get('params').favicon !== 'none' || app.get('params').favicon !== null) {
+    faviconPath = path.join(app.get('appDir'), app.get('params').staticsRoot, app.get('params').favicon)
+    if (fileExists(faviconPath)) {
+      app.use(require('serve-favicon')(faviconPath))
+    } else {
+      logger.warn(`${app.get('params').favicon} specified in favicon does not exist. Please ensure file is entered properly.`.yellow)
```
Comment (kethinov) [inline roosevelt.js]: Favicon images/favicon.ico does not exist. Please ensure the "favicon" param is configured correctly.

Comment (kethinov) [reply roosevelt.js]: Also change favicon default to "none" to suppress the warning. The generator can opt-in to favicons.

File: lib/jsCompiler.js (hunk 3 above)
Comment (kethinov) [reply lib/jsCompiler.js]: Change default for JS compiler to "none" to suppress the errors/warnings. The generator can opt-in to preprocessors.

File: lib/preprocessCss.js (hunk 4 above)
Comment (kethinov) [reply lib/preprocessCss.js]: Change default for CSS compiler to "none" to suppress the errors/warnings. The generator can opt-in to preprocessors.

File: defaultErrorPages/controllers/404.js [hunk 8]
```diff
@@ -1,12 +1,27 @@
...
+      <html lang='en'>
+        <head>
+          <meta charset='utf-8'>
+          <meta name='viewport' content='width=device-width,initial-scale=1'>
+          <meta name='format-detection' content='telephone=no'>
+          <title>404 Not Found</title>
+        </head>
+        <body>
+          <main>
+            <header role='banner'>
```
Comment (kethinov) [inline defaultErrorPages/controllers/404.js]: remove role='banner'

File: defaultErrorPages/controllers/404.js [hunk 9]
```diff
@@ -1,12 +1,27 @@
...
+              <h1>Not Found</h1>
+            </header>
+            <p>The requested URL ${req.url} was not found on this server.</p>
+            <footer role='contentinfo'>
```
Comment (kethinov) [inline defaultErrorPages/controllers/404.js]: remove role='contentinfo'

File: defaultErrorPages/controllers/503.js [hunk 10]
```diff
@@ -1,11 +1,26 @@
...
+    <html lang='en'>
+      <head>
+        <meta charset='utf-8'>
+        <meta name='viewport' content='width=device-width,initial-scale=1'>
+        <meta name='format-detection' content='telephone=no'>
+        <title>503 Service Unavailable</title>
+      </head>
+      <body>
+        <main>
+          <header role='banner'>
```
Comment (kethinov) [inline defaultErrorPages/controllers/503.js]: remove role='banner'

File: defaultErrorPages/controllers/503.js [hunk 11]
```diff
@@ -1,11 +1,26 @@
...
+            <h1>503 Service Unavailable</h1>
+          </header>
+          <p>The requested URL ${req.url} is temporarily unavailable at this time.</p>
+          <footer role='contentinfo'>
```
Comment (kethinov) [inline defaultErrorPages/controllers/503.js]: remove role='contentinfo'

File: defaultErrorPages/controllers/5xx.js [hunk 12]
```diff
@@ -1,12 +1,26 @@
...
+    <html lang='en'>
+      <head>
+        <meta charset='utf-8'>
+        <meta name='viewport' content='width=device-width,initial-scale=1'>
+        <meta name='format-detection' content='telephone=no'>
+        <title>${status} Internal Server Error</title>
+      </head>
+      <body>
+        <main>
+          <header role='banner'>
```
Comment (kethinov) [inline defaultErrorPages/controllers/5xx.js]: remove role='banner'

File: defaultErrorPages/controllers/5xx.js [hunk 13]
```diff
@@ -1,12 +1,26 @@
...
+            <h1>${status} Internal Server Error</h1>
+          </header>
+          <p>The requested URL ${req.url} is temporarily unavailable at this time.</p>
+          <footer role='contentinfo'>
```
Comment (kethinov) [inline defaultErrorPages/controllers/5xx.js]: remove role='contentinfo'

File: lib/htmlValidator.js [hunk 14]
```diff
@@ -224,102 +215,96 @@ module.exports = function (app, callback) {
...
-                } else if (errorLine.startsWith('Warning')) {
-                  if (errorArr[i + 1].startsWith('From line') || errorArr[i + 1].startsWith('At line')) {
-                    warningList += errorLine + '\n' + errorArr[i + 1] + '\n\n'
-                  } else {
-                    warningList += errorLine + '\n\n'
+      if (res.getHeader('Content-Type') && res.getHeader('Content-Type').includes('text/html') && !res.getHeader(headerException)) {
+        return body =>
+          new Promise((resolve) => {
+            options.data = body
+            console.log(options)
```
Comment (kethinov) [inline lib/htmlValidator.js]: ಠ_ಠ

File: README.md [hunk 15]
```diff
@@ -531,11 +535,21 @@ Statics parameters
 - `jsCompilerWhitelist`: Whitelist of JS files to compile as an array. Leave undefined to compile all files. Supply a `:` character after each file name to delimit an alternate file path and/or file name for the minified file.
   - Default: `null` (compiles all JS files, if a JS minifier is enabled).
   - Example: *[String]* `library-name/example.js:lib/example.min.js` (compiles `library-name/example.js` into `lib/example.min.js`).
+  - `jsCompilerBlacklist`: Array of JS files to exempt from minification. These files will be copied as is to the build folder. Leave undefined to compile all files.
```
Comment (kethinov) [inline README.md]: revise the whitelist language to match this new, better language: "Array of JS files to whitelist for minification."

Comment (kethinov) [inline README.md]: hyphenate as-is

File: README.md [hunk 16]
```diff
@@ -531,11 +535,21 @@ Statics parameters
...
+  - Default: `null` (compiles all JS files, if a JS minifier is enabled).
+  - Example: *[String]* `example.js`
+
 - `jsCompiledOutput`: Where to place compiled JS files. This folder will be symlinked into `public` by default.
   - Default: *[String]* `".build/js"`.
+
 - `nodeEnv`: *[String]* Param to override the `NODE_ENV` environment variable.
   - Default: `undefined`.
 
+- `generateFolderStructure`: When enabled Roosevelt will generate user specified directories (e.g. mvc, statics, build).
```
Comment (kethinov) [inline README.md]: When enabled Roosevelt will generate user specified directories (e.g. MVC parameters and statics parameters).

File: README.md [hunk 17]
```diff
@@ -146,7 +146,7 @@ Other useful scripts
 Run your app with a detached HTML validator instead of the default attached validator (runs validator as a separate process in the background; process must be manually killed later, see below):
 
 ```
-npm run dev detach-validator
+npm run dev -- -detach-validator
```
Comment (kethinov) [inline README.md]: updated requirements https://github.com/rooseveltframework/roosevelt/issues/290

File: defaultErrorPages/controllers/5xx.js [hunk 18]
```diff
@@ -1,12 +1,26 @@
...
   let status = err.status || 500
   res.status(status)
-  res.render(path.join(__dirname, '/../views/5xx'), {
-    status: status,
-    url: req.url,
-    mainDomain: req.headers['x-forwarded-host'] || req.headers.host,
-    appVersion: app.get('package').version
-  })
+  res.send(`
+    <!DOCTYPE html>
```
Comment (kethinov) [inline defaultErrorPages/controllers/5xx.js]: send the markup trimmed

minified too if possible but at least trimmed

File: defaultErrorPages/controllers/503.js [hunk 19]
```diff
@@ -1,26 +1,16 @@
...
+const path = require('path')
+const template = require('es6-template-strings')
+
 module.exports = function (app, req, res) {
+  let model = {
+    url: req.url,
+    mainDomain: req.headers['x-forwarded-host'] || req.headers.host,
+    appVersion: app.get('package').version
+  }
+  let errorTemplate = template(fs.readFileSync(path.join(__dirname, '../views/503.html')), model)
```
Comment (kethinov) [inline defaultErrorPages/controllers/503.js]: calling a readFile command on every error page is expensive and wasteful

File: README.md [hunk 20]
```diff
@@ -159,12 +176,14 @@ Or if your app is configured to detach the validator by default, you can force t
 ```
 npm run dev -- -attach-validator
 ```
+- `-a` can also be used.
 
-Run your app on two CPUs (default is `max`):
+Configure how many CPUs your app will run with. Can set to `max` to use all available CPUs. (Default is 1)
```
Comment (kethinov) [inline README.md]: "Configure how many CPUs your app will run on (default is `max`)."

yes we want the default to be max

File: README.md [hunk 21]
```diff
@@ -159,12 +176,14 @@ Or if your app is configured to detach the validator by default, you can force t
...
 
 ```
-node app.js -cores 2
+npm run dev -- --cores 2
 ```
+- `-c` can also be used.
```
Comment (kethinov) [inline README.md]: drop support for `-c`, it needs an argument and thus shouldn't be chained. keep `--cores`

File: lib/sourceFlags.js [hunk 22]
```diff
@@ -0,0 +1,111 @@
...
+              case 'h':
+                flags.enableValidator = true
+                break
+              case 'r':
+                flags.disableValidator = true
+                break
+              case 'b':
+                flags.backgroundValidator = true
+                break
+              case 'a':
```
Comment (kethinov) [inline lib/sourceFlags.js]: we need logic for what happens if these get chained in incoherent ways. what if i pass `-dphrba`?
