### PR TITLE
Fixed error with promise when html validator is disabled

### LINKED ISSUE #156: When validator is disabled it throws error because the promise is encapsulated
When validator is disabled it throws error because promise is encapsulated. Meaning the promise is only defined when the param for validation is set to true, so when we reach the [promise resolution code](https://github.com/rooseveltframework/roosevelt/blob/master/lib/htmlValidator.js#L173-L180) it errors because the promise doesn't exist when validation is disabled.

Two ways to solve this:

1. Wrap the promise resoultion at the bottom in the similar if statement found above
2. Go back to promise all (because it can accept an empty array), and give actual promise try catch handling before hand

### PR DESCRIPTION
**Pull request by JoshL18**
(closes #156)

**New pull request due to corruption of the last one.**

 Moved back to resolving the promise using Promise.all. This change:

- Fixes an error that occurs when the HTML validator has been turned off prior to launching the application.
- In the case that the HTML validator was turned off, the user is now told that the HTML validator is disabled and to check to make sure that their HTML validator is turned on.
- Makes it so that the HTML validator does not run when in production mode
- No longer checks for production mode within the HTML validator code

### CODE REVIEW

File: lib/sourceParams.js [hunk 1]
```diff
@@ -171,6 +171,7 @@ module.exports = function(app) {
 
   if (process.env.NODE_ENV === 'development') {
     params.noMinify = true;
+    params.enableValidator = false;
```
Comment (kethinov) [inline lib/sourceParams.js]: this is wrong

the check here is if prod mode enableValidator should be false

Comment (kethinov) [inline lib/sourceParams.js]: you will need a separate if statement

File: roosevelt.js [hunk 2]
```diff
@@ -138,6 +129,15 @@ module.exports = function(params) {
       require('./lib/jsCompiler')(app, mapRoutes);
     }
 
+     // initialize HTML validator
+    validateHTML();
+
+    function validateHTML() {
+      require('./lib/htmlValidator')(app, preprocessCss);
```
Comment (Autre31415) [inline roosevelt.js]: In order for this sequence of events to be changed `validateHTML();` needs to be removed and replaced with `preProcessCss();`, moved up to line 120 and the callbacks in each function altered to represent the changed sequence.  (With `compileJs` calling `validateHTML` and `validateHTML` calling `mapRoutes`, etc)

Comment (kethinov) [inline roosevelt.js]: yeah - just to be super clear: the goal here is to get the css/js parsing stuff to happen first, *then* begin starting the HTML validator so we change the order of the console output

File: lib/sourceParams.js [hunk 3]
```diff
@@ -137,6 +137,16 @@ module.exports = function(app) {
   app.set('cssCompiledOutput', path.normalize(appDir + params.cssCompiledOutput));
   app.set('jsCompiledOutput', path.normalize(appDir + params.jsCompiledOutput));
 
+  // keep track of state of env
+  if (process.env.NODE_ENV === 'development') {
+    // set the envStateDev to true if in dev mode
+    app.set('envStateDev', true);
```
Comment (kethinov) [inline lib/sourceParams.js]: we don't need to track this in an app var. querying `process.env.NODE_ENV` each time this is needed is fine

File: lib/htmlValidator.js [hunk 4]
```diff
@@ -170,12 +170,23 @@ module.exports = function(app, callback) {
...
-  }).catch(function(result) {
-    // rejection
-    console.error(('HTML Validator disabled. Continuing without HTML validation...').red);
-    validatorDisabled = true;
+  // only resolve promise when in dev mode
+  if (app.get('envStateDev')) {
+    Promise.all([promise]).then((result) => {
+      // only print error if validator is disabled and in dev mode
+      if (!params.enableValidator) {
+        console.error(('⚠️  ' + 'HTML validator disabled. Continuing without HTML validation...').yellow);
```
Comment (kethinov) [inline lib/htmlValidator.js]: this should be a warning

File: lib/htmlValidator.js [hunk 5]
```diff
@@ -170,12 +170,23 @@ module.exports = function(app, callback) {
...
+      }
+      callback();
+    }).catch((result) => {
+      // only print error if in dev mode
+      console.error(('⚠️  ' + 'HTML validator disabled. Continuing without HTML validation...').yellow);
```
Comment (kethinov) [inline lib/htmlValidator.js]: ditto here
